clean: true
author: polydice
author_url: https://github.com/polydice
github_url: https://github.com/polydice/ICInputAccessory
github_file_prefix: https://github.com/polydice/ICInputAccessory/blob/develop
xcodebuild_arguments: [-project, ICInputAccessory.xcodeproj, -scheme, ICInputAccessory-iOS]
module: ICInputAccessory
module_version: 2.0.0
output: docs
theme: fullwidth
skip_undocumented: true
